# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/icon.png

# Content configuration version
version: 2

# Personal info
name: Diego Sánchez Diéguez
title: Developer/SRE
email: diegosanchezdie@gmail.com
# email_title: Email (Email title override)
phone: 671 584 053
phone_title: Teléfono
website:
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username: parra28
stackoverflow_username:
dribbble_username:
facebook_username:
flickr_username:
instagram_username:
linkedin_username: diego-sanchez-dieguez-24111447
xing_username:
pinterest_username:
youtube_username:
googleplus_username:
orcid_username:

# Additional icon links
#additional_links:
#    - title: Link name
#      icon: https://fontawesome.com/icons?d=gallery&s=brands&m=free
#      url: https://google.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre mí
about_profile_image: images/perfil.jpg
about_content: | # this will include new lines to allow paragraphs
    Posee 7 años de experiencia profesional en los que ha efectuado principalmente labores
    de programación web en entornos de tramitación electrónica para la administración 
    pública. 

    Actualmente trabaja como desarrollador Full-Stack en proyectos relacionados 
    con Smart Cities encargada de la gestión eficiente, sostenible e inteligente de 
    múltiple sistemas IoT de servicios que serán implantados en el ámbito del 
    proyecto para el Ministerio de Economía y Empresas a través de Red.es.

content:
    #    - title: Proyectos # Title for the section
    #      layout: list # Type of content section (list/text)
    #      content:
    #          - layout: left
    #            title: Project name
    #            link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    #            link_text: Link Text
    #            additional_links:
    #                - title: Github page for project (eg. sproogen/modern-resume-theme)
    #                  icon: fab fa-github
    #                  url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    #                - title: Github page for project (eg. sproogen/modern-resume-theme)
    #                  icon: fab fa-github
    #                  url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
    #            quote: >
    #                Short overview of the project (optional)
    #            description: | # this will include new lines to allow paragraphs
    #                Description about the work on/with the project
    - title: Experiencia
      layout: list
      content:
          - layout: right
            title: Paradigma Digital
            sub_title: DevOps
            caption: Junio 2022 - Actualidad
            link: https://www.paradigmadigital.com/
            quote: >
                Después de 15 años de experiencia, de sumar más de 600 profesionales a nuestra familia y de trabajar mano a mano con 120 clientes, podemos decir que nos sentimos orgullosos de contribuir al éxito digital de las compañías más importantes de nuestro país. Si tu empresa es una empresa valiente, con una visión distinta; si es innovadora, capaz de recorrer caminos nuevos sin miedo; si está dispuesta a proponerse grandes desafíos…
            description: | # this will include new lines to allow paragraphs
                Encargado del ecosistema de Microsoft Azure DevOps para despliegues Databrick, RStudio ... .
          - layout: right
            title: IDOM
            sub_title: DevOps Engineer
            caption: Mayo 2021 - Junio 2022
            link: https://www.idom.com
            quote: >
                Empresa independiente que presta servicios profesionales de Consultoría, Ingeniería y Arquitectura, unidos en torno a una forma de hacer, unos objetivos comunes y al servicio de nuestros clientes.
            description: | # this will include new lines to allow paragraphs
                Desarrollo e implementación de plataformas para Smart Citie.
                - Virtualización de máquinas en VMWARE y OpenStack
                - Cluster de Kubernetes
                - Integración continua en Azure DevOps
                - Monitorización de máquinas.
                - Servicio centralizado de logs
          - layout: right
            title: IDOM
            sub_title: Full Stack Development
            caption: Marzo 2019 - Mayo 2021
            link: https://www.idom.com
            quote: >
                Empresa independiente que presta servicios profesionales de Consultoría, Ingeniería y Arquitectura, unidos en torno a una forma de hacer, unos objetivos comunes y al servicio de nuestros clientes.
            description: | # this will include new lines to allow paragraphs
                Encargado de desarrollo y administracion de sistemas de todo en el entorno Smart Cities.
          - layout: right
            title: Everis
            sub_title: Programador/a web
            caption: Noviembre 2018 - Febrero 2019
            link: https://www.everis.com
            quote: >
                Consultoría y outsourcing abarcando todos los sectores del ámbito económico.
            description: | # this will include new lines to allow paragraphs
                Programador Java web en el proyecto Vertidos de tramitación electrónica para la Consejería de Medio Ambiente.
          - layout: right
            title: Vipirsa
            sub_title: Programador Junior
            caption: Octubre 2017 - Octubre 2018
            link: https://vipirsa.com/
            #           quote: >
            #               Short description of the company (optional)
            description: | # this will include new lines to allow paragraphs
                Programador Java web en el proyecto Vertidos de tramitación electrónica para la Consejería de Medio Ambiente.
          - layout: right
            title: Servinform, S.A.
            sub_title: Programador Junior
            caption: Junio 2016 - Mayo 2017
            link: https://www.servinform.es/
            quote: >
                Especilistas en BPO, Atención y ventas, MK digital, soluciones tecnológicas y comunicación
            description: | # this will include new lines to allow paragraphs
                Programador web especializado en tramitación electrónica de la Junta de Andalucía
          - layout: right
            title: Sadiel S.A.
            sub_title: Programador Web
            caption: Abril 2012 - Julio 2012
            link: https://www.ayesa.com/es/
            quote: >
                Multinacional española especializada en ingeniería, tecnología y consultoría (ETC).
            description: | # this will include new lines to allow paragraphs
                Prácticas del Grado superior, desarrollador Java Web.
          - layout: right
            title: Innovas Sie S.L,L.
            sub_title: Técnico informático
            caption: Junio 2008 - Junio 2009
            #            link: Link to company (optional)
            quote: >
                Servicios Integrales a Empresas
            description: | # this will include new lines to allow paragraphs
                Venta y reparación de equipos informáticos.

    - title: Educación
      layout: list
      content:
          - layout: top-right
            title: Universidad Pablo de Olavide
            sub_title: Ingeniería informática en Sistemas de Información
            caption: 2012 - 2018
          #            quote: >
          #                Short institution or course description (optional)
          #            description: | # this will include new lines to allow paragraphs
          #                Description of qualification
          - layout: top-right
            title: I.E.S Poligono Sur
            sub_title: Desarrollo de Aplicaciones Informaticas
            caption: 2010 - 2012
          #            quote: >
          #                Short institution or course description (optional)
          #            description: | # this will include new lines to allow paragraphs
          #                Description of qualification
          - layout: top-right
            title: I.E.S Cantillana
            sub_title: Tecnico en Explotaciones de Sistemas Informáticos
            caption: 2006 - 2008
    #            quote: >
    #                Short institution or course description (optional)
    #            description: | # this will include new lines to allow paragraphs
    #                Description of qualification
#    - title: A Little More About Me
#      layout: text
#      content: | # this will include new lines to allow paragraphs
#          This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

#          Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
references_title: Referencias a petición

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
    sass_dir: _sass
    style: compressed

plugins:
    - jekyll-seo-tag

exclude:
    [
        "Gemfile",
        "Gemfile.lock",
        "node_modules",
        "vendor/bundle/",
        "vendor/cache/",
        "vendor/gems/",
        "vendor/ruby/",
        "lib/",
        "scripts/",
        "docker-compose.yml",
    ]
